const stops = [
  {
    day: 1,
    name: 'Recogida del coche en Madrid',
    lat: 40.4918,
    lng: -3.5695,
    description: 'Recoge tu coche en el aeropuerto de Madrid para comenzar el viaje hacia Peñafiel.',
    duration: '30 minutes',
    reservation: false,
    pricePerAdult: 0,
    startHour: '09:30',
    endHour: '10:00',
    date: '2024-07-04',
  },
  {
    day: 1,
    name: 'Viaje a Peñafiel',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Conduce desde Madrid a Peñafiel, un viaje de aproximadamente dos horas.',
    duration: '2 hours',
    reservation: false,
    pricePerAdult: 0,
    startHour: '10:00',
    endHour: '12:00',
    date: '2024-07-04',
  },
  {
    day: 1,
    name: 'Check-in en el hotel AF Pesquera',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Check-in en el hotel AF Pesquera, un elegante establecimiento vinculado al mundo del vino.',
    duration: '1 hour',
    reservation: true,
    reservationLink: 'https://www.afpesquera.com/',
    pricePerAdult: 150,
    startHour: '12:00',
    endHour: '13:00',
    date: '2024-07-04',
  },
  {
    day: 1,
    name: 'Almuerzo en Molino de Palacios',
    lat: 41.5917,
    lng: -4.1239,
    description: 'Disfruta de un almuerzo con asado local en el restaurante Molino de Palacios.',
    duration: '1-2 hours',
    reservation: true,
    reservationLink: 'https://www.molinodepalacios.es/',
    pricePerAdult: 30,
    startHour: '13:00',
    endHour: '15:00',
    date: '2024-07-04',
  },
  {
    day: 1,
    name: 'Castillo de Peñafiel y Museo del Vino',
    lat: 41.5932,
    lng: -4.1216,
    description: 'Visita al Castillo de Peñafiel y su museo dedicado al vino de la región.',
    duration: '1-2 hours',
    reservation: true,
    reservationLink: 'https://www.provinciadevalladolid.com/es/castillo-penafiel',
    pricePerAdult: 6,
    startHour: '15:00',
    endHour: '17:00',
    date: '2024-07-04',
  },
  {
    day: 1,
    name: 'Exploración libre por Peñafiel',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Tiempo libre para explorar Peñafiel a tu ritmo.',
    duration: '2 hours',
    reservation: false,
    pricePerAdult: 0,
    startHour: '17:00',
    endHour: '19:00',
    date: '2024-07-04',
  },
  {
    day: 1,
    name: 'Cena en el restaurante del hotel AF Pesquera',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Cena en el restaurante del hotel AF Pesquera, conocido por su excelente cocina local y vinos de la casa.',
    duration: '1-2 hours',
    reservation: true,
    reservationLink: 'https://www.afpesquera.com/',
    pricePerAdult: 50,
    startHour: '20:00',
    endHour: '22:00',
    date: '2024-07-04',
  },
  {
    day: 2,
    name: 'Desayuno en el hotel',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Disfruta del desayuno en el hotel antes de comenzar las actividades del día.',
    duration: '1 hour',
    reservation: false,
    pricePerAdult: 0,
    startHour: '08:00',
    endHour: '09:00',
    date: '2024-07-05',
  },
  {
    day: 2,
    name: 'Visita a Bodega Vega Sicilia',
    lat: 41.6176,
    lng: -4.2445,
    description: 'Tour y cata de vinos en la prestigiosa Bodega Vega Sicilia.',
    duration: '2-3 hours',
    reservation: true,
    reservationLink: 'https://www.vega-sicilia.com/',
    pricePerAdult: 60,
    startHour: '10:00',
    endHour: '13:00',
    date: '2024-07-05',
  },
  {
    day: 2,
    name: 'Almuerzo en Valbuena de Duero',
    lat: 41.6486,
    lng: -4.1887,
    description: 'Almuerzo en una bodega cercana o un restaurante en Valbuena de Duero.',
    duration: '1-2 hours',
    reservation: true,
    reservationLink: 'https://www.restaurantevaldevecilla.com/',
    pricePerAdult: 40,
    startHour: '13:00',
    endHour: '15:00',
    date: '2024-07-05',
  },
  {
    day: 2,
    name: 'Visita al Monasterio de Valbuena',
    lat: 41.6486,
    lng: -4.1887,
    description: 'Explora el Monasterio de Santa María de Valbuena y sus viñedos.',
    duration: '2 hours',
    reservation: true,
    reservationLink: 'https://www.monasteriodevalbuena.com/',
    pricePerAdult: 10,
    startHour: '15:00',
    endHour: '17:00',
    date: '2024-07-05',
  },
  {
    day: 2,
    name: 'Tiempo libre en el hotel',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Tiempo libre para relajarte en el hotel después de las visitas del día.',
    duration: '2 hours',
    reservation: false,
    pricePerAdult: 0,
    startHour: '17:00',
    endHour: '19:00',
    date: '2024-07-05',
  },
  {
    day: 2,
    name: 'Cena en un restaurante local',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Cena en un restaurante local recomendado por el hotel.',
    duration: '1-2 hours',
    reservation: true,
    reservationLink: 'https://www.afpesquera.com/',
    pricePerAdult: 50,
    startHour: '20:00',
    endHour: '22:00',
    date: '2024-07-05',
  },
  {
    day: 3,
    name: 'Desayuno en el hotel',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Disfruta del desayuno en el hotel antes de comenzar las actividades del día.',
    duration: '1 hour',
    reservation: false,
    pricePerAdult: 0,
    startHour: '08:00',
    endHour: '09:00',
    date: '2024-07-06',
  },
  {
    day: 3,
    name: 'Excursión al Parque Natural Hoces del Río Duratón',
    lat: 41.3000,
    lng: -3.8186,
    description: 'Realiza una excursión por el Parque Natural Hoces del Río Duratón, ideal para senderismo o paseos en bote.',
    duration: '3 hours',
    reservation: true,
    reservationLink: 'https://www.parquesnaturales.com/hoces-del-duraton',
    pricePerAdult: 0,
    startHour: '09:00',
    endHour: '12:00',
    date: '2024-07-06',
  },
  {
    day: 3,
    name: 'Visita a Bodega Protos',
    lat: 41.5932,
    lng: -4.1211,
    description: 'Tour y cata de vinos en Bodega Protos.',
    duration: '2 hours',
    reservation: true,
    reservationLink: 'https://www.protos.es/',
    pricePerAdult: 25,
    startHour: '12:00',
    endHour: '14:00',
    date: '2024-07-06',
  },
  {
    day: 3,
    name: 'Almuerzo en Peñafiel',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Almuerzo en Peñafiel o en una bodega cercana.',
    duration: '1-2 hours',
    reservation: true,
    reservationLink: 'https://www.afpesquera.com/',
    pricePerAdult: 30,
    startHour: '14:00',
    endHour: '16:00',
    date: '2024-07-06',
  },
  {
    day: 3,
    name: 'Visita a Aranda de Duero',
    lat: 41.6715,
    lng: -3.6890,
    description: 'Explora Aranda de Duero y sus bodegas subterráneas.',
    duration: '2-3 hours',
    reservation: true,
    reservationLink: 'https://www.rutadelvino-riberadelduero.es/',
    pricePerAdult: 10,
    startHour: '16:00',
    endHour: '19:00',
    date: '2024-07-06',
  },
  {
    day: 3,
    name: 'Regreso a Peñafiel',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Regreso al hotel en Peñafiel para descansar.',
    duration: '1 hour',
    reservation: false,
    pricePerAdult: 0,
    startHour: '19:00',
    endHour: '20:00',
    date: '2024-07-06',
  },
  {
    day: 3,
    name: 'Cena en el hotel o restaurante local',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Cena en el hotel o en otro restaurante local.',
    duration: '1-2 hours',
    reservation: true,
    reservationLink: 'https://www.afpesquera.com/',
    pricePerAdult: 50,
    startHour: '20:00',
    endHour: '22:00',
    date: '2024-07-06',
  },
  {
    day: 4,
    name: 'Desayuno en el hotel y check-out',
    lat: 41.5936,
    lng: -4.1200,
    description: 'Desayuno en el hotel y check-out antes de partir hacia Madrid.',
    duration: '1 hour',
    reservation: false,
    pricePerAdult: 0,
    startHour: '08:00',
    endHour: '09:00',
    date: '2024-07-07',
  },
  {
    day: 4,
    name: 'Visita rápida al mercado de Peñafiel',
    lat: 41.5929,
    lng: -4.1207,
    description: 'Visita rápida al mercado local para comprar productos típicos.',
    duration: '1 hour',
    reservation: false,
    pricePerAdult: 0,
    startHour: '09:00',
    endHour: '10:00',
    date: '2024-07-07',
  },
  {
    day: 4,
    name: 'Viaje a Riaza para almorzar',
    lat: 41.2790,
    lng: -3.4880,
    description: 'Conduce a Riaza para disfrutar de un almuerzo en Asador Matimore.',
    duration: '1-2 hours',
    reservation: true,
    reservationLink: 'https://www.asadormatimor.com/',
    pricePerAdult: 40,
    startHour: '13:00',
    endHour: '15:00',
    date: '2024-07-07',
  },
  {
    day: 4,
    name: 'Llegada a Madrid y tiempo libre',
    lat: 40.4168,
    lng: -3.7038,
    description: 'Llegada a Madrid y tiempo libre en la ciudad.',
    duration: '2 hours',
    reservation: false,
    pricePerAdult: 0,
    startHour: '15:00',
    endHour: '17:00',
    date: '2024-07-07',
  },
  {
    day: 4,
    name: 'Devolución del coche de alquiler en el aeropuerto',
    lat: 40.4918,
    lng: -3.5695,
    description: 'Devolución del coche de alquiler en el aeropuerto de Madrid.',
    duration: '1 hour',
    reservation: false,
    pricePerAdult: 0,
    startHour: '17:00',
    endHour: '18:00',
    date: '2024-07-07',
  },
  {
    day: 4,
    name: 'Vuelo de regreso a Palma',
    lat: 40.4918,
    lng: -3.5695,
    description: 'Vuelo de regreso a Palma de Mallorca desde Madrid.',
    duration: '2 hours',
    reservation: true,
    reservationLink: 'https://www.iberia.com/',
    pricePerAdult: 100,
    startHour: '19:00',
    endHour: '21:00',
    date: '2024-07-07',
  },
];

export default stops;
